### PR TITLE
Add support for array and nested object assertions

### LINKED ISSUE #5: Remove temporary workaround for traefik #10996
Remove the temporary workaround for https://github.com/traefik/traefik/issues/10996 once it's fixed.

Function `fixGH10996()`

### PR DESCRIPTION
**Pull request by WhySoBad**
Hi,
This pull request adds support for asserting claims which are of type array. It adds two new assertions: 
* **Contains**: Only authorize the user when the claims array contains this assertion string
* **ContainsAny**:  Only authorize the user when any entry assertion string array is also contained in the claims array

With the functionality to assert claim arrays it's now easily possible to for example assert an user role to authorize the user.

I have also introduced some changes to how claims are deserialized depending on their type:
* **Strings and Integers**: Those values are stringified when needed
* **Objects**: Recursively apply the same rules on the values of the object and append them using dot notation
* **Arrays**: Stringify all antries of the array

Using this change it's now possible to create assertions for nested object keys as the keys of objects are concatenated using a `.`

Additionally, I've removed the `version` from the `docker-compose.yml` as it's no longer needed with newer versions of docker compose and I updated `traefik` to `v3.1.4` which (somewhat unintentionally) fixed #5 

In some cases I'm not sure what's the most intuitive way to deserialize the claims. For example for claims which have arrays of objects we currently wouldn't support dot notation for the objects of the array but instead just stringify them. I could also imagine allowing support for something like `outer.inner[0].value` to also allow easy assertions on arrays of objects. Adding something like `outer.inner[0].value` would however make the validation somewhat more troublesome for what reason I didn't add it yet.

Please let me know what you think of these changes.

### CODE REVIEW

**Comment by sevensolutions** [comment]
Hi @WhySoBad,

many thanks for your contribution. Looks promising. I will do a closer review as soon as i have some time.

**Comment by sevensolutions** [comment]
Hmm.. Let me think of the cases we could have:

**Scalar Claim**
JWT:
```json
"preferred_username": "foo"
```
Config:
```yml
AssertClaims:
  - name: "preferred_username"
    anyOf: ["foo"]
```

**Array Claim**
JWT:
```json
"roles": ["foo", "bar", "xyz"]
```
Config:
```yml
AssertClaims:
  - name: "preferred_username"
    anyOf: ["foo"] # Would match
    anyOf: ["xyz"] # Would match
    anyOf: ["zzz"] # Would not match
    allOf: ["foo", "xyz"] # Would match
    allOf: ["foo", "zzz"] # Would not match
```

**Complex Object Claim**
JWT:
```json
"some": {
  "complex": {
    "val": ["foo", "bar", "xyz"]
  }
}
```
Config:
```yml
AssertClaims:
  - name: "some.complex.val"
    anyOf: ["foo"] # Would match
    anyOf: ["xyz"] # Would match
    anyOf: ["zzz"] # Would not match
    allOf: ["foo", "xyz"] # Would match
    allOf: ["foo", "zzz"] # Would not match
```

So: I think we can remove the `value` and `values` configuration options completely and only use `anyOf` and `allOf`.
You always need to specify an array, even if it's a single value but I'am happy with that to keep it simple.

@WhySoBad I can rework your PR if you want. Just 👍 if that's ok for you.

**Comment by sevensolutions** [comment]
Maybe we use https://pkg.go.dev/github.com/PaesslerAG/jsonpath instead of you own dot notation?
I don't know if it's compatible with yaegi but we can try.

**Comment by WhySoBad** [comment]
> So: I think we can remove the `value` and `values` configuration options completely and only use `anyOf` and `allOf`. You always need to specify an array, even if it's a single value but I'am happy with that to keep it simple.
> 
> @WhySoBad I can rework your PR if you want. Just 👍 if that's ok for you. Or just comment if you have time to do it by yourself :)

I agree with you. I think this solution is the best of both worlds. 


> Maybe we use https://pkg.go.dev/github.com/PaesslerAG/jsonpath instead of you own dot notation? I don't know if it's compatible with yaegi but we can try.

Yes using a package is probably a better solution. However, I see the following "edge case":
Let's assume I have the following object:
```typescript
{
  "some": [
    { "key": "111" },
    { "key": "222" }
  ]
}
```
Now, when I want to assert the array to contain an object with the value `222` for the key `key` I'd have to use a constant index: `$.some[1].key`
I think we should offer a solution like `$.some[x].key` which does not check for a constant index but any indices. The server which returns the claims may store the objects in a hash set in which case the order of the objects in the array is completely random.

I don't think we can achieve such a behavior using the package you mentioned. I've also found this package https://github.com/tidwall/gjson which would support this syntax enhancement and provide even more [syntactic sugars](https://github.com/tidwall/gjson/blob/master/SYNTAX.md) for the user without any implementation complexity on our side. 

If it's okay for you I'd finish this feature as it's a good way for me to learn a bit of go :)

**Comment by sevensolutions** [comment]
> Now, when I want to assert the array to contain an object with the value 222 for the key key I'd have to use a constant index: $.some[1].key
I think we should offer a solution like $.some[x].key which does not check for a constant index but any indices. The server which returns the claims may store the objects in a hash set in which case the order of the objects in the array is completely random.

Oh yes, i didn't thought about this case. 👍 

> If it's okay for you I'd finish this feature as it's a good way for me to learn a bit of go :)

Yes sure. Thank you very much for your work, as this is something I have wanted to do for a long time but have not gotten around to it yet.
I'am also in the middle of learning Go btw. 😉

**Comment by WhySoBad** [comment]
> I'am also in the middle of learning Go btw. 😉

Nice, after my experience with go in last advent of code it'll take some time for me to get to like go again. In my opinion it's missing a lot of functionality in the standard library which I enjoy from rust. For small projects like this it's pretty nice though 

I have kind of bad news: The `gjson` library makes use of the `unsafe` package which is [prohibited](https://github.com/traefik/traefik/issues/7459) by the traefik's yaegi configuration. However, `gjson` only requires unsafe functionality for [two functions](https://github.com/tidwall/gjson/issues/18#issuecomment-271602895) which we don't really need. It might be a bit sketchy but we could put the `gjson` package into the vendored directory and then comment out this functionality which is not needed. 

I'm also considering creating an issue in the `gjson` repository and ask for advice since the issue linked above is very old and there was another [issue](https://github.com/tidwall/gjson/issues/19) which mentioned a `gjson-safe` package but this can't be found anymore and it is also very old. 

I'd like to stick to the `gjson` package as it seems like the perfect fit for our needs and offers some flexibility for the users which I think is very nice

**Comment by sevensolutions** [comment]
Ok yes, give *ajson* a try. Just as a hint: For traefik, all 3rd party libs need to be vendored, but i would much appreciate it if we don't need to patch anything.

I also had the idea of rewriting the entire plugin to WebAssembly because 1. it's compiled and faster, 2. i can use all 3rd party libs so i also don't need to implement OIDC by myself.
But i haven't used WebAssembly already so i decided to keep it as it is for right now.

**Comment by WhySoBad** [comment]
> Ok yes, give _ajson_ a try. Just as a hint: For traefik, all 3rd party libs need to be vendored, but i would much appreciate it if we don't need to patch anything.

Yes, I think patching in a vendored library is very sketchy

> I also had the idea of rewriting the entire plugin to WebAssembly because 1. it's compiled and faster, 2. i can use all 3rd party libs so i also don't need to implement OIDC by myself. But i haven't used WebAssembly already so i decided to keep it as it is for right now.

Ouh, I totally forgot about WebAssembly traefik plugins. This sounds really interesting as the benefits are obvious. Sadly, I'm not familiar with WebAssembly either but I might have a look at it in the future (as it would also allow writing plugins in rust :eyes:)

Anyways, I've now implemented the matching using `ajson` and changed the assertions to only use the `AllOf` and `AnyOf` quantifiers. In my opinion the `ajson` package does a great job for our purpose. I've also added some examples to the README which allow for a quick overview of what can be achieved using json path assertion names. 

It's possible to combine `AnyOf` and `AllOf` quantifiers. Since a name like `store.book[*].price` yields multiple matches with every match being a single float it's also possible to specify the `AllOf` quantifier for matching non-array values.

**Comment by sevensolutions** [comment]
Thx for reworking the code using ajson.
I'am just playing around with your code a bit and here are two things i've found:

1. An empty AllOf ignores AnyOf. Example:
```yml
AssertClaims:
  - Name: preferred_username
    AnyOf: ["admin", "xy"] 
```
So if i login as "foo" for example, i'am authorized and see the following message:
`Authorized claim preferred_username: Found all values of []`

I think this happens because the `allMatches` array will then be empty and therefore `if !slices.Contains(allMatches, false)` will always be true.

2. Can you please re-add the code for showing the available claims in the log?
I think this makes debugging easier when you want to configure the authorization.

**Comment by WhySoBad** [comment]
>Can you please re-add the code for showing the available claims in the log?
>I think this makes debugging easier when you want to configure the authorization.

Yes those messages are indeed really helpful when debugging. I accidentally removed those lines when rebasing and fixing merge conflicts

I've now moved the `isAuthorized(...)` method to the `augorization.go` file and added tests for it in the `authorization_test.go` file. I think the most common cases (including some edge cases) should be covered by those tests. Writing the tests was certainly a good decision as I already found some bugs (including the one you mentioned) whilst writing the tests.

Additionally, I've added a github workflow which runs testing in CI on every push. Since this repository is public you have unlimited free action minutes so why don't verify on every pust the authorization still works as expected. Maybe you can even add a rule for pull requests which enforces successful testing before being able to merge.

**Comment by sevensolutions** [comment]
@WhySoBad thank you.. Looks good now 👍 
If you're also happy with it, i will merge it.

**Comment by WhySoBad** [comment]
Yes, I'm happy with the current state of this pull request. You can go on and merge it :+1: 

Will this in addition to the PKCE be enough for a new release? I'd love to be able to use these new features without having to rely on local plugins in my setup :)

**Comment by sevensolutions** [comment]
> Will this in addition to the PKCE be enough for a new release? I'd love to be able to use these new features without having to rely on local plugins in my setup :)

Yes, since i don't have any other features planned yet, i'll publish a new release of the current features.
I'll do that tomorrow, probably.

**Pull request merged**
